//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GülBlogMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBLOGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBLOGS()
        {
            this.TBLCOMMENT = new HashSet<TBLCOMMENT>();
        }
    
        public int ID { get; set; }
        public string BLOGTITLE { get; set; }
        public string BLOGDES { get; set; }
        public string BLOGPIC { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string SLUG { get; set; }
        public Nullable<int> VIEWS { get; set; }
    
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        public virtual TBLUSERS TBLUSERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCOMMENT> TBLCOMMENT { get; set; }
    }
}
