//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GülBlogMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTACT
    {
        public int ID { get; set; }
        public string ABOUTUS { get; set; }
        public string ADDRESS { get; set; }
        public string NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string MAP { get; set; }
        public string TWITTER { get; set; }
        public string INSTAGRAM { get; set; }
        public string GITHUB { get; set; }
        public string LINKEDIN { get; set; }
    }
}
