//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GülBlogMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUSERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUSERS()
        {
            this.TBLBLOGS = new HashSet<TBLBLOGS>();
        }
    
        public int ID { get; set; }
        public string NAMEANDSURNAME { get; set; }
        public string PASS { get; set; }
        public string PICTURE { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string USERNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBLOGS> TBLBLOGS { get; set; }
        public virtual TBLROLE TBLROLE { get; set; }
    }
}
